version: '3'

services:
  api:
    container_name: fofx-go-gin-prod 
    environment:
      - GO_ENV=production
      - URI=https://api.example.com/
      - DOMAIN=example.com
      - FRONTEND_URI=https://example.com/
      - PORT=3001
    command: go run cmd/server/main.go
    ports:
      - "3030:3001"
    build: 
      context: .
      dockerfile: Dockerfile
    restart:
      always
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: fofx-go-gin-prod-db
    platform: linux/x86_64
    image: mariadb:latest 
    restart: always
    tty: true
    volumes:
      - ./prod-data/sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

